LoginWithAuthenticationTest/Models/CompanyOffer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWithAuthenticationTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CompanyOffer
    {
        public int CompanyOfferID { get; set; }
        public int CompanyID { get; set; }
        public int LanguageID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Location { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Description { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Language Language { get; set; }
    }
}

LoginWithAuthenticationTest/Controllers/CompanyOffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LoginWithAuthenticationTest.Models;
using Microsoft.AspNet.Identity;

namespace LoginWithAuthenticationTest.Controllers
{
    public class CompanyOffersController : Controller
    {
        private jobEntities1 db = new jobEntities1();
        private ApplicationUserManager _userManager;

        // GET: CompanyOffers
        public ActionResult Index()
        {
            var companyOffer = db.CompanyOffer.Include(c => c.Company).Include(c => c.Language);
            return View(companyOffer.ToList());
        }

        // GET: CompanyOffers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyOffer companyOffer = db.CompanyOffer.Find(id);
            if (companyOffer == null)
            {
                return HttpNotFound();
            }
            return View(companyOffer);
        }

        // GET: CompanyOffers/Create
        public ActionResult Create()
        {
            ViewBag.CompanyID = new SelectList(db.Company, "CompanyID", "CompanyGUID");
            ViewBag.LanguageID = new SelectList(db.Language, "LanguageID", "Name");
            return View();
        }

        // POST: CompanyOffers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyOfferID,CompanyID,LanguageID,Price,Location,Experience,Description")] CompanyOffer companyOffer)
        {
            var userId = User.Identity.GetUserId();
            var company = db.Company.FirstOrDefault(p => p.CompanyGUID == userId);
            if(company == null)
            {
                return HttpNotFound();
            }
            companyOffer.CompanyID = company.CompanyID;
            if (ModelState.IsValid)
            {
                db.CompanyOffer.Add(companyOffer);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            ViewBag.CompanyID = new SelectList(db.Company, "CompanyID", "CompanyGUID", companyOffer.CompanyID);
            ViewBag.LanguageID = new SelectList(db.Language, "LanguageID", "Name", companyOffer.LanguageID);
            return View(companyOffer);
        }

        // GET: CompanyOffers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyOffer companyOffer = db.CompanyOffer.Find(id);
            if (companyOffer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyID = new SelectList(db.Company, "CompanyID", "CompanyGUID", companyOffer.CompanyID);
            ViewBag.LanguageID = new SelectList(db.Language, "LanguageID", "Name", companyOffer.LanguageID);
            return View(companyOffer);
        }

        // POST: CompanyOffers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyOfferID,CompanyID,LanguageID,Price,Location,Experience,Description")] CompanyOffer companyOffer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyOffer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyID = new SelectList(db.Company, "CompanyID", "CompanyGUID", companyOffer.CompanyID);
            ViewBag.LanguageID = new SelectList(db.Language, "LanguageID", "Name", companyOffer.LanguageID);
            return View(companyOffer);
        }

        // GET: CompanyOffers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyOffer companyOffer = db.CompanyOffer.Find(id);
            if (companyOffer == null)
            {
                return HttpNotFound();
            }
            return View(companyOffer);
        }

        // POST: CompanyOffers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanyOffer companyOffer = db.CompanyOffer.Find(id);
            db.CompanyOffer.Remove(companyOffer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LoginWithAuthenticationTest/Views/CompanyOffers/Create.cshtml
@model LoginWithAuthenticationTest.Models.CompanyOffer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","CompanyOffers", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyOffer</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        


        <div class="form-group">
            @Html.LabelFor(model => model.LanguageID, "Linguagem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LanguageID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LanguageID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginWithAuthenticationTest/Views/CompanyOffers/Delete.cshtml
@model LoginWithAuthenticationTest.Models.CompanyOffer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyOffer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Company.CompanyGUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyGUID)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Language.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LoginWithAuthenticationTest/Views/CompanyOffers/Details.cshtml
@model LoginWithAuthenticationTest.Models.CompanyOffer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CompanyOffer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyOfferID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LoginWithAuthenticationTest/Views/CompanyOffers/Edit.cshtml
@model LoginWithAuthenticationTest.Models.CompanyOffer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyOffer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyOfferID)

        @*<div class="form-group">
            @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @Html.HiddenFor(model => model.CompanyID)

        
        <div class="form-group">
            @Html.LabelFor(model => model.LanguageID, "Linguagem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LanguageID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LanguageID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginWithAuthenticationTest/Views/CompanyOffers/Index.cshtml
@model IEnumerable<LoginWithAuthenticationTest.Models.CompanyOffer>

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Company.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Experience)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Company.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Experience)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>

        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CompanyOfferID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CompanyOfferID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanyOfferID })
        </td>*@
    </tr>
}

</table>